# Numpy


# NumPy is a Python library

# NumPy is used for working with arrays

# NumPy is short for Numerical Python

In [121]:
# Numpy 
import numpy as np


In [122]:
1+1

2

In [123]:
lst=[1,2,3,4]
arr=np.array(lst)

In [124]:
arr

array([1, 2, 3, 4])

In [125]:
type(arr)

numpy.ndarray

In [126]:
arr.shape

(4,)

In [127]:
arr1=np.array([[1,2,3],[4,5,6]])

In [128]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
# 2 dimension
arr1.shape

(2, 3)

In [130]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [131]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [132]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [133]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
arr1.dtype

dtype('int32')

In [135]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [136]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [137]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [138]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [139]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [140]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [142]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [143]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [144]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [145]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [146]:
print("Random number generation(Uniform distribution)")
np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.15302628, 0.8928956 , 0.79883653],
       [0.62931899, 0.1379332 , 0.23381874]])

In [147]:
print("Random number following a Normal distribtuion with mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a Normal distribtuion with mean=0 and std=1
[[ 0.82916121 -0.73925609 -0.92085914]
 [ 0.198444   -1.29792661 -0.41250802]
 [ 0.01928685  2.54666605 -0.06343862]
 [-0.64713634  0.41876677  0.47402472]
 [-0.56962237 -0.84121939 -0.93233882]]


In [148]:
np.random.randint(1,100,50)

array([ 5, 26, 97, 95,  1, 47, 24, 76, 10, 13, 99, 24, 35, 79, 88, 21, 59,
       47, 13, 71, 77, 76, 30, 49, 85, 94, 49, 33, 33, 92, 47, 64, 70, 61,
        4, 94, 27, 82, 68, 35, 14, 40, 17, 86, 65, 15, 89, 15, 98,  6])

In [149]:
np.random.randint(1,100,(4,4))

array([[30, 84, 99, 24],
       [35, 38, 98, 14],
       [28, 30, 14, 21],
       [61, 49, 70,  4]])

In [150]:
arr=np.arange(0,11)

In [151]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
## Slicing

arr[2:7:3]

array([2, 5])

In [153]:
arr[-1:7:-1]

array([10,  9,  8])

In [154]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [155]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [156]:
arr1

array([[36, 84,  2, 59],
       [93, 47, 72, 54],
       [43, 21,  4, 28],
       [72, 58, 20, 96],
       [51,  3,  5, 10]])

In [157]:
arr1[3:,1:]

array([[58, 20, 96],
       [ 3,  5, 10]])

In [158]:
arr1[0:3,0:3]

array([[36, 84,  2],
       [93, 47, 72],
       [43, 21,  4]])

In [159]:
arr1[-3:-1,-3:-1]



array([[21,  4],
       [58, 20]])

In [160]:
## universal functions

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [161]:
arr1

array([[85, 72, 70],
       [95, 59,  4],
       [20, 74, 28]])

In [162]:
arr2

array([[78, 87, 23],
       [33, 48, 47],
       [49, 41, 81]])

In [163]:
arr1+arr2

array([[163, 159,  93],
       [128, 107,  51],
       [ 69, 115, 109]])

In [164]:
arr1 *arr2

array([[6630, 6264, 1610],
       [3135, 2832,  188],
       [ 980, 3034, 2268]])

In [165]:
arr1 / arr2

array([[1.08974359, 0.82758621, 3.04347826],
       [2.87878788, 1.22916667, 0.08510638],
       [0.40816327, 1.80487805, 0.34567901]])

In [166]:
np.sqrt(arr1)

array([[9.21954446, 8.48528137, 8.36660027],
       [9.74679434, 7.68114575, 2.        ],
       [4.47213595, 8.60232527, 5.29150262]])

In [167]:
np.exp(arr2)

array([[7.49841700e+33, 6.07603023e+37, 9.74480345e+09],
       [2.14643580e+14, 7.01673591e+20, 2.58131289e+20],
       [1.90734657e+21, 6.39843494e+17, 1.50609731e+35]])

In [168]:
np.log10(arr1)

array([[1.92941893, 1.8573325 , 1.84509804],
       [1.97772361, 1.77085201, 0.60205999],
       [1.30103   , 1.86923172, 1.44715803]])

In [232]:
arr1=np.arange(1,10)

In [234]:
arr1[2:]=1000

In [171]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [228]:
arr1 = arr1.reshape(3, 3)
np.dot(arr1, arr2)


array([[ 49144,  41183,  81117],
       [160000, 176000, 151000],
       [160000, 176000, 151000]])

In [230]:
arr1 = arr1.reshape(3, 3)
# arr2 should already be (3, 3)
result = np.matmul(arr1, arr2)


In [236]:
print(np.__version__)


1.26.4
